# experiment description
exp_name: 'ant_4legged'

# environment description
exp_env_name: 'Ant_4legged-v0'
exp_epi_len: 1000
exp_demo_file_name: 'ant_4legged'

# architecture description
pi_hidden_layers: [256, 256]

# option
# 0-element: batchnorm ('batch-norm' means we use batch normalization)
# 1-element: activation function ('relu', 'leaky-relu', 'sigmoid', 'tanh')
# 2-element: last activation function ('default' means nothing, 'sigmoid', 'tanh')
pi_options: ['default', 'leaky-relu', 'default']


# SAC hyperparameters
replay_size: 100000
gamma: 0.99
polyak: 0.995
alpha: 0.2
acc_threshold: 0.999

# training hyperparameters
learning_rate: 0.001
epochs: 1000
steps_per_epoch: 4000
batch_size: 256
n_log_epi: 10
start_steps: 10000
update_after: 1000
update_every: 50
save_interval: 10
plot_rendering: True

# seed
seed: 1
